spring:
  datasource:
    url: jdbc:mysql://localhost/api_users?useSSL=false
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddlAuto: update
  jackson:
    timeZone: America/Mexico_City
    locale: es_MX
  servlet:
    multipart:
      # Maximo archivos permitidos
      max-file-size: 15MB
      # Maximo archivos permitidos en la solicitud request
      max-request-size: 15MB
logging:
  level:
    org:
      hibernate:
        SQL: debug